### ISSUE TITLE
MeteringUsageResult.Quantity must be double, not long

### ISSUE THREAD

**Issue by lostmsu** [Azure/Commercial-Marketplace-SaaS-Accelerator#101]
**Describe the bug**

```
System.Text.Json.JsonException: The JSON value could not be converted to System.Int64. Path: $.result[0].quantity | LineNumber: 0 | BytePositionInLine: 342.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int64.
   at System.Text.Json.Utf8JsonReader.GetInt64()
   at System.Text.Json.Serialization.Converters.JsonConverterInt64.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Microsoft.Marketplace.SaaS.SDK.Client.Network.WebRequestHelper.BuildResultFromResponse[T]() in D:\a\1\s\src\SaaS.SDK.Client\Network\WebRequestHelper.cs:line 166
   at Microsoft.Marketplace.SaasKit.Network.AbstractSaaSApiRestClient`1.DoRequest(String url, String method, Dictionary`2 parameters, Dictionary`2 headers, String contentType) in D:\a\1\s\src\SaaS.SDK.Client\Network\AbstractSaaSApiRestClient.cs:line 87
   at Microsoft.Marketplace.SaasKit.Services.MeteredBillingApiClient.EmitBatchUsageEventAsync(IEnumerable`1 subscriptionBatchUsageRequest) in D:\a\1\s\src\SaaS.SDK.Client\Services\MeteredBillingAPIClient.cs:line 95
```

**To Reproduce**
Submit `MeteringUsageRequest` with non-integer `Quantity`

**Expected behavior**
`Emit` should succeed

**Comment by msalemcode** [comment]
This issue was fixed with PR #524
