### ISSUE TITLE
MeteredTriggerJob failing due to Unhandled exception

### ISSUE THREAD

**Issue by rd-snow17** [Azure/Commercial-Marketplace-SaaS-Accelerator#771]
[10/07/2024 07:00:00 > 726658: SYS INFO] Status changed to Initializing
[10/07/2024 07:00:01 > 726658: SYS INFO] Run script 'MeteredTriggerJob.exe' with script host - 'WindowsScriptHost'
[10/07/2024 07:00:01 > 726658: SYS INFO] Status changed to Running
[10/07/2024 07:00:06 > 726658: INFO] MeteredExecutor Webjob Started at: 10/7/2024 7:00:05 AM
[10/07/2024 07:00:06 > 726658: ERR ] Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
[10/07/2024 07:00:06 > 726658: ERR ]    at System.IO.Path.GetFullPath(String path)
[10/07/2024 07:00:06 > 726658: ERR ]    at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
[10/07/2024 07:00:06 > 726658: ERR ]    at Marketplace.SaaS.Accelerator.MeteredTriggerJob.Program.Main(String[] args) in /home/rohit/deployDev/Commercial-Marketplace-SaaS-Accelerator-us-uk/src/MeteredTriggerJob/Program.cs:line 45
[10/07/2024 07:00:06 > 726658: SYS INFO] Status changed to Failed
[10/07/2024 07:00:06 > 726658: SYS ERR ] Job failed due to exit code -532462766

**Comment by santhoshb-msft** [comment]
@fthorntonai  can you please look into this?

**Comment by rd-snow17** [comment]
> @rd-snow17 are you working from the 7.6.2 or 8.0.0 tag/branch ?

@fthorntonai , we had upgraded our accelerator to 8.0.0 using the upgrade script mentioned in the doc
